name = "pokemon-pokedex"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "10"
name = "pokemon-pokedex"
compatibility_date = "2024-01-01"

[env.production]
name = "pokemon-pokedex"

[[env.production.routes]]
pattern = "*"