name = "pokemon-pokedex"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "service-worker"
dir = "dist"
main = "./dist/index.html"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html", "**/*.css"]

[[build.upload.rules]]
type = "Data"
globs = ["**/*.json", "**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg", "**/*.ico"]